### ISSUE TITLE
tgresolve function not work

### ISSUE THREAD

**Issue by brightoneqq** [kamikazechaser/tg-resolve#19]
It seems the lib not work now . I am using the latest version lib and have a bare resolve .
However , it return error . Any idea about this issue ?
```
    console.log(result.id);
                       ^

TypeError: Cannot read property 'id' of undefined
    at /Users/chenjunjie/nodeJs_workspace/tg.js:18:24
    at Request._callback (/Users/chenjunjie/nodeJs_workspace/node_modules/tg-resolve/index.js:46:20)
    at Request.self.callback (/Users/chenjunjie/nodeJs_workspace/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/Users/chenjunjie/nodeJs_workspace/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/Users/chenjunjie/nodeJs_workspace/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)

**Comment by maxwowpow** [comment]
check the value of `error` first, before checking the result.

I have
`Error: Username not found
    at Request._callback (/rbd/pnpm-volume/c04aa120-8d4a-42fa-a65c-b3105971ffa8/node_modules/.registry.npmjs.org/tg-resolve/1.3.1/node_modules/tg-resolve/index.js:45:21)`
`    at Request.self.callback (/rbd/pnpm-volume/c04aa120-8d4a-42fa-a65c-b3105971ffa8/node_modules/.registry.npmjs.org/request/2.88.0/node_modules/request/request.js:185:22)`

**Comment by maxwowpow** [comment]
@kamikazechaser are there any requirements to the api token?

**Comment by kamikazechaser** [comment]
This library is deprecated. I may rewrite it in the future using tdlib. TDLib compilation is still a pain.

**Comment by ghost** [comment]
@kamikazechaser when you rewrite tg-resolve library

**Comment by kamikazechaser** [comment]
@NMIFUN If I find compiled TDCli binaries it may be worth a shot again.
